# Generated by Django 4.2.6 on 2023-12-13 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_alter_animal_options_alter_photo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_photos', to='animals.animal', verbose_name='Животное'),
        ),
    ]
