# Generated by Django 4.2.6 on 2023-12-23 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us_app', '0003_alter_developer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developer',
            options={'verbose_name': 'Разработчик', 'verbose_name_plural': 'Разработчики'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Описание', 'verbose_name_plural': 'Описания'},
        ),
    ]
