# Generated by Django 4.2.6 on 2023-11-09 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.IntegerField(verbose_name='Идентификатор устройства')),
                ('device_name', models.CharField(blank=True, max_length=100, verbose_name='Имя устройства')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
            },
        ),
        migrations.CreateModel(
            name='DeviceMeasurements',
            fields=[
                ('measurement_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор измерения')),
                ('cumulative_angle', models.FloatField(verbose_name='Накопленный угол')),
                ('pressure', models.FloatField(verbose_name='Атмосферное давление')),
                ('altitude', models.FloatField(verbose_name='Высота над уровнем моря')),
                ('temperature', models.FloatField(verbose_name='Температура окружающей среды')),
                ('humidity', models.FloatField(verbose_name='Влажность воздуха')),
                ('taser_activations', models.IntegerField(verbose_name='Количество активаций тазера')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='dashboard.devices', verbose_name='Устройства')),
            ],
            options={
                'verbose_name': 'Измерение',
                'verbose_name_plural': 'Измерения устройств',
            },
        ),
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_charge', models.FloatField(verbose_name='Уровень заряда батареи')),
                ('satellite_count', models.IntegerField(verbose_name='Количество спутников')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('inside_or_not', models.BooleanField(verbose_name='Внутри или снаружи')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='dashboard.devices', verbose_name='Устройства')),
            ],
            options={
                'verbose_name': 'Информация об устройстве',
                'verbose_name_plural': 'Информация об устройствах',
            },
        ),
    ]
