# Generated by Django 4.2.6 on 2023-12-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_devices_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemeasurements',
            name='cumulative_angle',
            field=models.FloatField(verbose_name='Температура за °F'),
        ),
        migrations.AlterField(
            model_name='devicemeasurements',
            name='temperature',
            field=models.FloatField(verbose_name='Температура за °C'),
        ),
    ]
