# Generated by Django 4.2.6 on 2023-12-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_devicemeasurements_cumulative_angle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceinfo',
            name='battery_charge',
            field=models.FloatField(null=True, verbose_name='Уровень заряда батареи'),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='satellite_count',
            field=models.IntegerField(null=True, verbose_name='Количество спутников'),
        ),
        migrations.AlterField(
            model_name='devicemeasurements',
            name='altitude',
            field=models.FloatField(null=True, verbose_name='Высота над уровнем моря'),
        ),
        migrations.AlterField(
            model_name='devicemeasurements',
            name='cumulative_angle',
            field=models.FloatField(null=True, verbose_name='Температура за °F'),
        ),
        migrations.AlterField(
            model_name='devicemeasurements',
            name='humidity',
            field=models.FloatField(null=True, verbose_name='Влажность воздуха'),
        ),
        migrations.AlterField(
            model_name='devicemeasurements',
            name='pressure',
            field=models.FloatField(null=True, verbose_name='Атмосферное давление'),
        ),
        migrations.AlterField(
            model_name='devicemeasurements',
            name='taser_activations',
            field=models.IntegerField(null=True, verbose_name='Количество активаций тазера'),
        ),
        migrations.AlterField(
            model_name='devicemeasurements',
            name='temperature',
            field=models.FloatField(null=True, verbose_name='Температура за °C'),
        ),
    ]
