# Generated by Django 4.2.6 on 2023-12-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_deviceinfo_battery_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceinfo',
            name='inside_or_not',
            field=models.BooleanField(null=True, verbose_name='Внутри или снаружи'),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='latitude',
            field=models.FloatField(null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='longitude',
            field=models.FloatField(null=True, verbose_name='Долгота'),
        ),
    ]
