# Generated by Django 4.2.6 on 2023-11-21 11:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_devices_device'),
        ('notices', '0002_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='battery_charge',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='location_status',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='satellite_count',
        ),
        migrations.AlterField(
            model_name='notification',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.device', verbose_name='Устройство'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время'),
        ),
    ]
