# Generated by Django 4.2.6 on 2023-12-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_remove_notification_battery_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='viewed',
            field=models.BooleanField(default=False, verbose_name='Просмотрено'),
        ),
    ]
