# Generated by Django 4.2.6 on 2023-11-13 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_devices_device'),
        ('geoapp', '0004_alter_geozone_options_alter_geozone_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geozone',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geo_zones', to='dashboard.device', verbose_name='Устройство'),
        ),
    ]
