# Generated by Django 4.2.6 on 2023-12-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mqttconnection',
            name='mqtt_broker',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Брокер'),
        ),
        migrations.AlterField(
            model_name='mqttconnection',
            name='mqtt_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='mqttconnection',
            name='mqtt_port',
            field=models.PositiveIntegerField(verbose_name='Порт'),
        ),
        migrations.AlterField(
            model_name='mqttconnection',
            name='mqtt_username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя пользователя'),
        ),
    ]
